apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: dotfiles
build:
  artifacts:
    - image: dotfiles-test-machine
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - test-machine.yml
