#!/usr/bin/env ruby

unless File.directory? File.expand_path("../../rebase-merge", __FILE__)
  camera = ""
  cameraList = `imagesnap -l`.split("\n")
  cameraIndex = cameraList.index{|c| c.include?("C920")}

  if cameraIndex != nil && cameraIndex > -1
    cameraName = cameraList[cameraIndex].sub("=> ", "")
    camera = "-d \"#{cameraName}\""
  end

  file = "~/Dropbox/commitfaces/#{Time.now.strftime("%Y-%m-%d_%H%M%S")}.jpg"
  system "imagesnap -q #{camera} -w 1 #{file} &"
end

exit 0
