[general]
import = ["C:\\Users\\zoee\\AppData\\Roaming\\alacritty\\catppuccin-mocha.toml"]
working_directory = "C:\\Users\\zoee\\Developer"

[terminal.shell]
program = "powershell"

[font]
# normal = { family = "FiraMono Nerd Font", style = "Bold" }
normal = { family = "0xProto Nerd Font", style = "Regular" }
size = 11

[keyboard]
bindings = [
{ key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
]
